config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "products#index"
  resources :order_items
  resources :products
  resource :cart, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :orders
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  before_save :update_total
  before_create :update_status

  def calculate_total
    self.order_items.collect { |item| item.product.price * item.quantity }.sum
  end

  private

  def update_status
    if self.status == nil?
      self.status = "In progress"
    end
  end

  def update_total
    self.total_price = calculate_total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

end

app/models/product.rb
class Product < ApplicationRecord
  validates :price, :name, :presence => true
  has_many :order_items

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :account
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :create_new_account

  def create_new_account
    self.create_account()
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception
  helper_method :current_order
  helper_method :current_user

  def current_order
    if session[:order_id]
      Order.find(session[:order_id])
    else
      Order.new
    end
  end

  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :avatar) }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @order_items = current_order.order_items
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  def create
    @order = current_order
    @item = @order.order_items.new(item_params)
    @order.save
    session[:order_id] = @order.id
    redirect_to products_path
  end

  def destroy
    @order = current_order
    @item = @order.order_items.find(params[:id])
    @item.destroy
    @order.save
    redirect_to cart_path
  end

  private

  def item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @books = Book.new.api_call

    @products = Product.all
    @order_item = current_order.order_items.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/show.html.erb
<% if @order_items.any? %>
  <% @order_items.each do |item| %>
    <p><%= item.product.name %> | <%= link_to "Delete", order_item_path(item), :data => {:confirm => "You sure?", :method => "delete"} %></p>
    <p> Unit Price: <%= number_to_currency item.product.price %> | Quantity: <%= item.quantity %> | Total Price: <%= number_to_currency (item.product.price * item.quantity) %></p>
  <% end %>
  <p>Your Total: <%= number_to_currency current_order.total_price %></p>
<% else %>
  <p>Your shopping cart is empty.</p>
<% end %>

app/views/home/index.html.erb
<%= render "layouts/products" %>

app/views/layouts/_navigation.html.erb
<div class="nav-fixed">
  <nav>
    <div class="nav-wrapper">
      <a class="brand-logo" href="/">HOME</a>
      <ul id="nav-mobile" class="left ">
        <li><%= link_to "SIGN UP", new_user_registration_path %></li>
        <li><%= link_to "SIGN IN", new_user_session_path %> <%= current_order.order_items.count %></li>
        <li><%= link_to "Cart", cart_path %></li>
        <% if current_user %>
          <li>Hello, <%=current_user.name %>
            <%= link_to "SIGN OUT", destroy_user_session_path, :method => :delete %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_products.html.erb
<div id="products" class="transitions-enabled">
  <div class="container">
    <div class="row">
      <% @products.each do |product| %>
      <div class="col s12 m4">
        <div class="card">
          <div class="card-content">
            <span class="card-title"><%= product.name %> | <%= number_to_currency product.price %></span>
            <p>I am a very simple card. I am good at containing small bits of information.</p>
          </div>
          <div class="card-action">
            <%= form_for @order_item do |f| %>
            <%= f.hidden_field :product_id, value: product.id %>
            <div class="row">

              <div class="col s6">
                <%= f.number_field :quantity, value: 1 %>
              </div>
              <div class="col s6">
                <%= f.submit "Add to cart" %>
              </div>
            </div>
            <% end %></p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoryTime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body> <div class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <a href="/" class="brand-logo"><i class="material-icons logo-icon nav-logo">book</i></a>
        <ul class="right">
          <% if !current_user %>
            <li><%= link_to "SIGN UP", new_user_registration_path %></li>
            <li><%= link_to "SIGN IN", new_user_session_path %></li>
            <li><%= link_to "Cart", cart_path %></li>
          <% end %>
          <% if current_user %>
            <li><%= link_to "SIGN OUT", destroy_user_session_path, :method => :delete %><li>
            <li><%= link_to "#{current_user.name}'s Cart", cart_path %></li>
          <%end%>
        </ul>
      </div>
    </nav>
  </div>
  <div class="content">
    <%= yield %>
  </div>
  </body>

</html>

app/views/products/index.html.erb
<div class="container">
  <div class="card">
    <h1>TOp Sellers</h1>
    <div class="card-content">
      <ol>
        <% @books.each do |book| %>
        <li><%="#{book["title"]} by #{book["author"]}"%> </li>
        <% end %>
      </ol>

    </div>

  </div>
</div>
<%= render "layouts/products" %>